//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IKotomasyon
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class IKEntities : DbContext
    {
        public IKEntities()
            : base("name=IKEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<tblGirisEkrani> tblGirisEkranis { get; set; }
        public virtual DbSet<tblIzinIslemleri> tblIzinIslemleris { get; set; }
        public virtual DbSet<tblMaasIslemleri> tblMaasIslemleris { get; set; }
        public virtual DbSet<tblMesaiIslemleri> tblMesaiIslemleris { get; set; }
        public virtual DbSet<tblPersonelIslemleri> tblPersonelIslemleris { get; set; }
        public virtual DbSet<tblPrimIslemleri> tblPrimIslemleris { get; set; }
    }
}
