//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IKotomasyon
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblIzinIslemleri
    {
        public int izinID { get; set; }
        public int personelID { get; set; }
        public Nullable<int> izinTipi { get; set; }
        public Nullable<int> izinGunSayisi { get; set; }
        public System.DateTime izinBaslangicTarihi { get; set; }
        public System.DateTime izinBitisTarihi { get; set; }
    
        public virtual tblPersonelIslemleri tblPersonelIslemleri { get; set; }
    }
}
