//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IKotomasyon
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMaasIslemleri
    {
        public int personelMaasID { get; set; }
        public int personelID { get; set; }
        public int personelMesaiID { get; set; }
    
        public virtual tblMesaiIslemleri tblMesaiIslemleri { get; set; }
        public virtual tblPersonelIslemleri tblPersonelIslemleri { get; set; }
    }
}
