//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IKotomasyon
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPersonelIslemleri
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblPersonelIslemleri()
        {
            this.tblIzinIslemleris = new HashSet<tblIzinIslemleri>();
            this.tblMaasIslemleris = new HashSet<tblMaasIslemleri>();
            this.tblMesaiIslemleris = new HashSet<tblMesaiIslemleri>();
            this.tblPrimIslemleris = new HashSet<tblPrimIslemleri>();
        }
    
        public int personelID { get; set; }
        public string personelTc { get; set; }
        public string personelAdi { get; set; }
        public string personelSoyadi { get; set; }
        public string personelTel { get; set; }
        public string personelAdres { get; set; }
        public string personelDepartman { get; set; }
        public string personelGorevi { get; set; }
        public string personelDurum { get; set; }
        public string personelIban { get; set; }
        public decimal personelNetMaas { get; set; }
        public System.DateTime personelGirisTarihi { get; set; }
        public System.DateTime personelCikisTarihi { get; set; }
        public System.DateTime personelDogumTarihi { get; set; }
        public decimal personelBrütMaas { get; set; }
        public decimal personelGunlukMaas { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblIzinIslemleri> tblIzinIslemleris { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblMaasIslemleri> tblMaasIslemleris { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblMesaiIslemleri> tblMesaiIslemleris { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPrimIslemleri> tblPrimIslemleris { get; set; }
    }
}
